import type { Metadata } from "next";

/** The public production origin. Used where the brand URL must not change per env. */
export const PRODUCTION_SITE_URL = "https://bolecapital.in";
/**
 * Origin of the current deployment, inlined at build time by next.config.ts
 * from the SITE_URL env var (e.g. https://test.bolecapital.in in CI test jobs).
 * Drives metadataBase, canonical/og:url, og:image, sitemap and JSON-LD, so link
 * previews on non-prod hosts point at their own /opengraph-image.
 */
export const SITE_URL: string = process.env.SITE_URL || PRODUCTION_SITE_URL;
/** Non-production builds are kept out of search indexes. */
export const IS_PRODUCTION_SITE = SITE_URL === PRODUCTION_SITE_URL;
export const SITE_NAME = "Bole Capital";
export const SITE_DESCRIPTION =
  "Bole Capital helps individuals and families build and protect wealth through a disciplined, long-term approach.";

/**
 * Last git commit date (ISO), inlined at build time by next.config.ts via
 * src/lib/lastUpdated.ts. Drives the footer date and sitemap.xml <lastmod>.
 * Falls back to "now" outside a Next build (e.g. unit tests).
 */
export const SITE_LAST_UPDATED: string =
  process.env.SITE_LAST_UPDATED || new Date().toISOString();

export const CONTACT = {
  email: "hello@bolecapital.in",
  telephone: ["+91-7827301069", "+91-9971301069"],
  address: {
    streetAddress: "",
    addressLocality: "Dhanbad",
    addressRegion: "Jharkhand",
    postalCode: "826001",
    addressCountry: "IN",
  },
  sameAs: [
    "https://www.instagram.com/bolecapital",
    "https://www.linkedin.com/company/bolecapital",
  ],
} as const;

type PageSeo = {
  /** Short page title; the root layout template appends " - Bole Capital". */
  title: string;
  description: string;
  /** Path relative to the site root, e.g. "/about". */
  path: string;
  keywords?: string[];
};

/**
 * Shared social preview generated by src/app/opengraph-image.tsx. Child
 * segments that define `openGraph` lose the file-based image (metadata is
 * shallow-merged), so pageMetadata references it explicitly.
 */
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${SITE_NAME}, AMFI-registered Mutual Fund Distributor in Dhanbad`,
} as const;

/**
 * Per-page metadata with canonical URL, Open Graph and Twitter tags.
 * Nested `openGraph`/`twitter` objects replace (not merge with) the layout's,
 * so the shared fields are repeated here.
 */
export function pageMetadata({ title, description, path, keywords }: PageSeo): Metadata {
  return {
    title,
    description,
    keywords,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      locale: "en_IN",
      url: path,
      title: `${title} - ${SITE_NAME}`,
      description,
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: `${title} - ${SITE_NAME}`,
      description,
      images: [OG_IMAGE.url],
    },
  };
}

export const absoluteUrl = (path: string) => new URL(path, SITE_URL).toString();
